//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_stert { get; set; }
        public string description { get; set; }
        public int status_id { get; set; }
    
        public virtual status status { get; set; }
        public virtual User User { get; set; }
    }
}
