//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_start { get; set; }
        public string descriprion { get; set; }
        public int statud_id { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
